version: "3.7"

networks:
  postgres:

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: trans_test_task_311
    user: docker:www-data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - ./src:/app

  postgres:
    image: postgres:12.2-alpine
    networks:
      - postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    networks:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

